apiVersion: apps/v1
kind: Deployment
metadata:
  name: azaks-kubernetes
spec:
  selector:
    matchLabels:
      name: azaks-kubernetes
  template:
    metadata:
      labels:
        name: azaks-kubernetes
    spec:
      containers:
        - name: app
          image: municontainers.azurecr.io/henry:v1
          ports:
            - containerPort: 8080
