apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
     app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
        - name: dotnet-webapp
          image: blaize/webapplication1
          ports:
            - containerPort: 80
